NORMAL = 'NORMAL'
TOO_LOW = 'TOO_LOW'
TOO_HIGH = 'TOO_HIGH'
LOWER_LIMIT = 'LOWER_LIMIT'
UPPER_LIMIT = 'UPPER_LIMIT'
PASSIVE_COOLING = 'PASSIVE_COOLING'
HI_ACTIVE_COOLING = 'HI_ACTIVE_COOLING'
MED_ACTIVE_COOLING = 'MED_ACTIVE_COOLING'
COOLING_TYPE = 'coolingType'
CONTROLLER_ALERT = 'TO_CONTROLLER'
EMAIL_ALERT = 'TO_EMAIL'
RECEPIENT = "a.b@c.com"
COOLING_LIMITS = {
    PASSIVE_COOLING: {
        LOWER_LIMIT: 0,
        UPPER_LIMIT: 35
    },
    HI_ACTIVE_COOLING:{
        LOWER_LIMIT: 0,
        UPPER_LIMIT: 45
    },
    MED_ACTIVE_COOLING:{
        LOWER_LIMIT: 0,
        UPPER_LIMIT: 40
    }
}
