NORMAL = 'NORMAL'
TOO_LOW = 'TOO_LOW'
TOO_HIGH = 'TOO_HIGH'
LOWER_LIMIT = 'LOWER_LIMIT'
UPPER_LIMIT = 'UPPER_LIMIT'
PASSIVE_COOLING = 'PASSIVE_COOLING'
HI_ACTIVE_COOLING = 'HI_ACTIVE_COOLING'
MED_ACTIVE_COOLING = 'MED_ACTIVE_COOLING'
VALUE = "VALUE"
RESULT = "RESULT"
ALERT_TARGET = "ALERT_TARGET"
COOLING_TYPE = 'COOLING_TYPE'
BREACH_TYPE = 'BREACH_TYPE'
CONTROLLER_ALERT = 'TO_CONTROLLER'
EMAIL_ALERT = 'TO_EMAIL'
RECEPIENT = "a.b@c.com"
EMAIL_LOW_TEMPERATURE = 'Hi, the temperature is too low'
EMAIL_HIGH_TEMPERATURE = 'Hi, the temperature is too high'
NO_BREACH = "No Breach"
UNSUPPORTED_ALERT_TARGET = "Alert Target not supported"
COOLING_LIMITS = {
    PASSIVE_COOLING: {
        LOWER_LIMIT: 0,
        UPPER_LIMIT: 35
    },
    HI_ACTIVE_COOLING:{
        LOWER_LIMIT: 0,
        UPPER_LIMIT: 45
    },
    MED_ACTIVE_COOLING:{
        LOWER_LIMIT: 0,
        UPPER_LIMIT: 40
    }
}
